### ISSUE TITLE
キー入力で大文字のアルファベットを押しても小文字に認識され、Zを押しても終了しなくなった

### ISSUE THREAD

**Issue by MIN0** [akio-se/msxterm#5]
以下のZ80アセンブラファイルをMSX-BASICに変換して、MSXTERMに#loadしましたが、最新レヴィジョンのMSXTERMで次の現象が起こるようになりました。  
  
キーボードを押すと、そのキーキャラクタを表示するZ80プログラム。  
大文字のZを押すと終了する。  
ところが、大文字のアルファベットを押しても小文字に認識され、Zを押しても終了しなくなった。  
最新のMSXTERMでこの現象が起こった。それ以前のレヴィジョンでは起こらなかった。  
  
ちなみに、lowsend_offにする方法を知らないので、設定していません。  
  
その時のプログラムを以下に示します。よろしくお願いします。  
  
0000                            ORG       0000H  
009F                  L009F     EQU       009FH  
00A2                  L00A2     EQU       00A2H  
D000                  LD000     EQU       0D000H  
0000  CD   9F00       L0000     CALL      L009F  
0003  FE   5A                   CP        5AH  
0005  C8                        RET       Z  
0006  CD   A200                 CALL      L00A2  
0009  47                        LD        B,A  
000A  3E   3D                   LD        A,3DH  
000C  CD   A200                 CALL      L00A2  
000F  78                        LD        A,B  
0010  CB   2F                   SRA       A  
0012  CB   2F                   SRA       A  
0014  CB   2F                   SRA       A  
0016  CB   2F                   SRA       A  
0018  C6   30                   ADD       A,30H  
001A  CD   A200                 CALL      L00A2  
001D  78                        LD        A,B  
001E  E6   0F                   AND       0FH  
0020  C6   30                   ADD       A,30H  
0022  CD   A200                 CALL      L00A2  
0025  3E   0A                   LD        A,0AH  
0027  CD   A200                 CALL      L00A2  
002A  3E   0D                   LD        A,0DH  
002C  CD   A200                 CALL      L00A2  
002F  C3   00D0                 JP        LD000  
0031                            END       L0000

**Comment by akio-se** [comment]
ここに説明を書いているのですが一度 #lowsend_off で試して頂けますか？
https://github.com/akio-se/msxterm#lowsend_on
https://github.com/akio-se/msxterm#lowsend_off

やはりドキュメントを読まない人が多いことを考えると、デフォルトで #lowsend_on はやめておいた方がいいんでしょうかね。

**Comment by MIN0** [comment]
ドキュメントをちゃんと読んでなくて（興味持ったとこばかり読んでました）ごめんなさいです。  
#lowsend_offするとちゃんと動きました。今回テストに使ったプログラムはあまり仕様を読んでないで作られたプログラムだと思います。  
小さなアセンブラプログラムだとそこまで考えてないと思うのでoffの状態にしてあったほうがいいかもしれません。  
が、判断に迷うところです。教えていただいてありがとうございました。  
チェックした時の出力結果をご参考までつけておきます。  
  
```
Ok  
> #lowsend_off  
Lower Case send mode Off  
  
> run  
run  
> a  
a=61  
=0=  
> A  
A=41  
=0=  
> z  
z=7:  
=0=  
> Z  
Ok  
  
> #lowsend_on  
Lower Case send mode On  
> run  
run  
> a  
a=61  
=0=  
> A  
a=61  
=0=  
> z  
z=7:  
=0=  
> Z  
z=7:  
=0=  
> #quit  
  
```

**Comment by akio-se** [comment]
MSX0 製品版リリースに伴い、文字コードの問題が解決して送受信速度も問題なくなりました。
このため小文字で送信する機能そのものが不要となりましたので ver.0.4 以降はデフォルトで off となります。
現状ではコマンドそのものは残っていますが、いずれ廃止の予定です。
