### ISSUE TITLE
テスト（REDCLK(01F5H/SUB)を使用）で想定外の現象が起きます

### ISSUE THREAD

**Issue by MIN0** [akio-se/msxterm#7]
MIN0です。こんにちは。  
  
MSXDOS.SYS、COMMAND.COMをHRA!さんにいただいて、テストを行いました。  
私はMSXマシンはM5stack+MSXしか持っていないので、MSXTERMでテストしています。  
足し算を繰り返して、実行時間を測ろうとしています。  
ところが、分秒などの時間表示処理で苦戦しています。教えてもらえませんか？  
  
テスト（REDCLK(01F5H/SUB)…CLOCK-ICのデータの読み出しのみを実行）と参考資料は以下です。  
  
＜参考資料＞  
MSXテクハンwiki　6章CLOCKとバッテリーバックアップ  
http://ngs.no.coocan.jp/doc/wiki.cgi/TechHan?page=6%BE%CF+CLOCK%A4%C8%A5%D0%A5%C3%A5%C6%A5%EA%A5%D0%A5%C3%A5%AF%A5%A2%A5%C3%A5%D7%A1%A6%A5%E1%A5%E2%A5%EA  
  
  
~~~
REDCLK	equ	01F5H  
RC0		equ	000h  
EXTROM	equ	015FH  
  
	org 0d000h  
  
	ld		c,RC0  
	call	REDCLK1  
	add		A,030h  
	ld		e,a  
  
;テストのためこれ以降は省略  
  
	ret  
  
REDCLK1:  
	push	IX  
    LD    IX, REDCLK   ;Set BIOS entry address  
    CALL  EXTROM       ;Returns here  
    and		00fh  
    pop		IX  
	ret  
end  
~~~
  
  
それを実行してみたのが次です。  
  
  
~~~
192.168.1.105:2223  
history.txt  
Connecting... 192.168.1.105:2223  
connected.  
  
MSX-DOS version 1.03  
Copyright 1984 by Microsoft  
  
COMMAND version 1.11  
  
> dir  
A>dir  
MSXDOS   SYS    2432 85-08-23  
COMMAND  COM    6656 85-09-02  
AUTOEXEC _AT      10 23-06-24  
RABBITRY COM   30525 23-06-18  
README   TXT     497 23-06-24  
HFORTH   COM   13671 23-06-04  
SAMPLE01 4TH      16 23-07-05  
ED       COM    7409 00-07-06  
TEST07   COM      20 23-07-10  
TEST06   COM      78 23-07-10  
TEST08   COM     247 23-07-14  
TEST10   COM      70 23-07-16  
TEST11   COM      23 23-07-16  
      13 files  
  658432 bytes free  
> test11  
A>test11  
      13 files  
>  
~~~
  
  
実行したプログラムはもっといろいろ処理を書いていましたが、簡単にするためにREDCLKだけにしています。実行しても何も表示されないはずですが、なぜか今まで出力された最後の行が出力されています。  
  
これはMSX-DOS側の問題なのか、MSXTERM側の問題なのかわからないでいます。  
何か思いつくことがあればお教え願います。  
  
  
　MIN0

**Comment by akio-se** [comment]
一応確認です。
MSX-DOのメモリマップは全部RAMになっていると思います。
DOSのシステムコールがあるのは 0000H から 0100H の間で、0100H以降は何も無いと思います。
EXTROM の 015FH をコールしようとしていますがちゃんと動いていますか?

「2.2.3 MSX-DOSからのSUB ROMコール」が正しく呼び出されているか確認お願いします。

http://ngs.no.coocan.jp/doc/wiki.cgi/datapack?page=2%BE%CF+%A5%A4%A5%F3%A5%BF%A1%BC%A5%B9%A5%ED%A5%C3%A5%C8%A5%B3%A1%BC%A5%EB

**Comment by MIN0** [comment]
私が理解が浅いために混乱させて申し訳ありません。元々はファンクションコールがわかっていなくて、時間のカウントの呼び出しで失敗ばかりしているためにEXTROMにも時間のカウントがあったのでやってみて失敗ばかりしていました。  
別でも同様の質問をしていて、ファンクションコールはこうやればいいと間違っているところを教わりました。これで時間のカウントがうまくできるか試してみるつもりです。EXTROMも大事な（指摘された100Hを超えるところへの呼び出しをどうやるのかは、考えてもいませんでした。教えてくださってありがとうございました）知識ですので、先の方で理解したいと思います。  
どうもありがとうございました😊

**Comment by MIN0** [comment]
すみません、今回の質問はMSXTERMと関係なかったので削除しましょうか？

**Comment by akio-se** [comment]
それではこのチケットは誤報という事でクローズしますね。

とりあえず一旦 BASIC と MSX-DOS は別物と考えて、ROMのAPI ではなく MSX-DOS の API を学習するといいと思います。
「MSX DATAPACK」をまとめた webもありますし、PDFでも配布されています。
（MSX-DOSの元になったCP/Mの情報も参考になると思います）

「MSX-DOSからのSUB ROMコール」の話もありましたが、ROMを無理に使うよりはMSX-DOS の ファンクションコールで「時刻の獲得」が用意されているのでそれを使うのが簡単だと思いますよ。
